on:
  pull_request:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: 
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum

      - name: Unit Tests
        run: go test ./... -v
